### ISSUE TITLE
请教tab目录切换与详情列表加载的实现

### ISSUE THREAD

**Issue by riddle911** [Ghostdar/wechat-weapp-vueForum#1]
老哥，仔细阅读了您的代码，加上我自己也在做类似的小程序，有点疑惑还望能解答下：

我是自己有个小论坛，然后暴露了各种api出来，目前做的程度是
在header的类别中，通过wx.request获取host.com/api/categories,得到目录名称然后渲染出来，目录切换使用的也是查询e.target.id做的；

主要遇到问题是，我的header里如何做到绑定不同路由呢，

我现在header的类别一栏中 设置了两种：一个是 “最新”帖子，其json地址为：host.com/api/recent
另外就是不同版块的json地址： host.com/api/category/{某种特定id}/{版块名称}

这样就涉及到请求不同路由加载内容详情的问题，我看一般类似的程序大家都是请求的单独一个url，通过判断id什么的做不同的路由更改，那你看我现在要是实现切换tab时，请求不同路由，这个应该按什么思路实现呢？网上搜索了好几天都不得要领，还请您指点一二。

**Comment by Ghostdar** [comment]
@riddle911  你使用过vue吗？可以直接使用[mpvue](https://github.com/Meituan-Dianping/mpvue)这个框架开发。

**Comment by riddle911** [comment]
谢谢~mpvue只听说过，还没用。
我去看看相关文档看是否能搞定吧 谢谢您给出思路~~
